from typing import Iterator, Any

class Reader:
    def __init__(self) -> None: ...
    def log_level(self, level: int) -> None: ...
    def seek_cursor(self, cursor: str) -> None: ...
    def get_next(self) -> dict[str, Any]: ...
    def get_previous(self) -> dict[str, Any]: ...
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
